.PHONY: clean All

All:
	@echo "----------Building project:[ UOCTaxation - Debug ]----------"
	@cd "UOCTaxation" && "$(MAKE)" -f  "UOCTaxation.mk"
clean:
	@echo "----------Cleaning project:[ UOCTaxation - Debug ]----------"
	@cd "UOCTaxation" && "$(MAKE)" -f  "UOCTaxation.mk" clean
